[package]
name = "scratch"
version = "0.1.0"
edition = "2021"

[dependencies]
nom.workspace = true
nom_locate.workspace = true
nom-supreme.workspace = true
thiserror.workspace = true
miette.workspace = true
itertools.workspace = true

semver = "1.0"
